# ------------------------------------------------------------------------------
#          ---        
#        / o o \    Project:  cov-armee
#        V\ Y /V    Config file BEAST2 tree simulation + inference analyses
#    (\   / - \     
#     )) /    |     
#     ((/__) ||     Code by Ceci VA 
# ------------------------------------------------------------------------------

run:
  # glm_vs_nn:
  #   simulation:
  #     - "glm_vs_nn"
  #   inference:
  #     - "glm_vs_nn"
  singletype_3sr_glm:
    simulation: 
      - "singletype_3sr_glm"
    inference:
      # - "bd_3sr"
      # - "glm_3sr"
      - "glm_3sr_fixorig"
      # - "nn_3sr" # You can have several analyses here and it will run everything

  

beast:
  command_sim: "beast"
  # command_sim: "java -jar /Users/ceciliav/Tools/beast-code/GLMPrior/out/artifacts/GLMPrior/GLMPrior.jar"
  command_inf: "beast"
  action: "overwrite"
  chains: 1
  chain_length: 10000000
  log_every: 1000
  time: 7200
  mem_mb: 4096
  threads: 2
  
config_analyses: "config/analyses.yaml"


